// @require     file://<path>\src\code\02_declarations.js
// @require     file://<path>\src\code\03_handleAnime.js
// @require     file://<path>\src\code\04_animeObject.js
// @require     file://<path>\src\code\05_helper.js
// @require     file://<path>\src\code\06_checkdata.js
// @require     file://<path>\src\code\07_bookmarks.js
// @require     file://<path>\src\code\08_Mal2kiss.js
// @require     file://<path>\src\code\09_malBookmarks.js
// @require     file://<path>\src\code\10_kissDropdown.js
// @require     file://<path>\src\code\11_miniMAL.js
// @require     file://<path>\src\code\89_init.js
// @require     file://<path>\src\code\91_external.js